### PR TITLE
Create dw.com.ini

### PR DESCRIPTION
**Pull request by doglover3920**
**------------------------------------------------------------------------------------------------
* @header_start
* WebGrab+Plus ini for grabbing EPG data from TvGuide websites
* @Site: dw.com
* @MinSWversion: V2
* @Revision 0 - [02/06/2017] doglover
*  - creation
* @Remarks: 
* @header_end
**------------------------------------------------------------------------------------------------
site {url=dw.com|timezone=GMT|maxdays=7.1|cultureinfo=en|charset=UTF-8|titlematchfactor=90}
site {keepindexpage}
url_index{url ()|http://www.dw.com/epg/data/4765/1/|subpage|}
url_index.headers {customheader=Accept-Encoding=gzip,deflate}
urldate.format {datenumber|java}
global_temp_1.modify {calculate (format=date,java)|'urldate'}
global_temp_2.modify {calculate (scope=urlindex format=F0)|'config_timespan_days' 1 + 6 *} 
subpage.format{list(step=14400000 count='global_temp_2')|'global_temp_1'}

index_variable_element.modify {addstart()|data-channel-id="'config_site_id'}
index_variable_element.modify {remove|)}

index_showsplit.scrub {multi (includeblock="'index_variable_element'")|<div class="channelElements clearfix|<div class="epgProgram||}
index_showsplit.modify {cleanup(removeduplicates)}
*
index_temp_1.scrub {single|data-day="||"}
index_temp_2.scrub {single|data-begin-time="||"}
index_start.modify {addstart ()|'index_temp_1' 'index_temp_2}
index_title.scrub {single|<h2 class="title">||</h2}
index_title.modify {cleanup(tags="<"">")}
index_description.scrub {single|<ul class="topics">||</ul}
index_description.modify {replace|<li>| ##BR## }
index_description.modify {cleanup(tags="<"">")}
index_description.modify {cleanup}
index_description.modify {replace|##BR##|\n}
index_description.modify {replace|##BR#|}
index_description.modify {replace|\n |\n}

index_urlshow {url|http://www.dw.com|<a href="||">}
title.modify {addstart|'index_title'}
description.scrub {single|h4>Aktuelle Folge</h4>|<p>|</p>|<a href="javascript}
description.modify {addstart ('description' not "")|\n\n}

**  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _
**      #####  CHANNEL FILE CREATION (only to create the xxx-channel.xml file)
**
** @auto_xml_channel_start
*index_site_id.scrub {multi()|}
*index_site_id.modify {addstart|1\|5\|2\|3\|4}
*index_site_channel.modify {addstart|DW(English)\|DW(Deutsch)\|DW(Deutsch+)\|DW(Español)\|DW(Arabic)}
** @auto_xml_channel_end

### CODE REVIEW

**Comment by Netuddki** [comment]
dw.com was dw.de and I updated it a few days ago and it's already in the list for Germany :-)

**Comment by SilentButeo2** [comment]
So this one can be close?
Or is this an international version for this site?

**Comment by Netuddki** [comment]
The ini I created has all the international Deutsche Welle channels.

Deutsche Welle IS only an international channel. There is no local channel of it in Germany.

**Comment by Netuddki** [comment]
@doglover3920 
I also didn't say that yours doesn't have them.

I just explained that those channels are all international versions and my ini have them all.

Next time please check the list before you work on something, because I updated many inis lately.

It doesn't do any good if we work parallel on the same thing.

**Comment by doglover3920** [comment]
And mine had them too.

But you are the boss...

**Comment by Netuddki** [comment]
I'm by far not the boss. Exactly the opposite. I am the @sshole here.

The real bosses will decide what happens anyway. I just tried to give an advice, so we don't work in crossover. :-)

**Comment by doglover3920** [comment]
I obvious missed your version.  If you know me, you would have known I would gladly be using yours, instead of writing a new one.

You stated:  The ini I created has all the international Deutsche Welle channels.
Well so had mine.

Case closed?

**Comment by Netuddki** [comment]
I stated that because SilentButeo2 asked if this is an international version, suggesting the possibility that mine was the ini for the regular version. Only that's why I explained, that also mine has the international versions, suggesting that both inis are basically the same.

I was just clarifying the situation. It was in no way degrading your ini or trying to attack you in some way.
If you have read something like that into my text, I'm sorry.

Case closed.

**Pull request closed without merging**
