### PR TITLE
Update bein.net.ini

### PR DESCRIPTION
**Pull request by Netuddki**

### CODE REVIEW

**Comment by SilentButeo2** [comment]
add new header?

**Comment by Netuddki** [comment]
Actually I just added a 0 to the url. I don't even know if it really does something, but probably not. I think a new header would be unnecessary.

**Comment by SilentButeo2** [comment]
Ok, if you don't know what it does, I'll just close this one

**Comment by Netuddki** [comment]
LOL
I didn't add it just randomly.
Of course I know what it's supposed to do, but I am not sure that it really affects the outcome.
On the website it did, in the xml it didn't.
I added it for being on the safe side, but whatever you think is right.

**Comment by SilentButeo2** [comment]
Being a php param, I think it's just default to 0. So
url_index{url|http://epg.beinsports.com/utctime##country##.php?cdate=|urldate|&offset=0&category=##genre##&id=123}
could also be
url_index{url|http://epg.beinsports.com/utctime##country##.php?cdate=|urldate|&category=##genre##&id=123}
But if you change the siteini, you must change the header. (only for comments changes can be done without header change)

**Comment by Netuddki** [comment]
Ok, understood

**Pull request closed without merging**
