### PR TITLE
radiotimes times aren't UTC, correct wrong season scrubbing

### PR DESCRIPTION
**Pull request by olivluca**
they are UK times, the timezone must be Europe/London

### CODE REVIEW

**Comment by olivluca** [comment]
I only know that with the original radiotimes.com.ini this is the output I get

```
 <programme start="20190414210000 +0000" stop="20190414220000 +0000" channel="BBC One HD">
 <title lang="en">Line of Duty</title>
```
(wrong)

with my patch

```
<programme start="20190414210000 +0100" stop="20190414220000 +0100" channel="BBC One HD">
<title lang="en">Line of Duty</title>

```
(correct)

**Comment by olivluca** [comment]
The time given by ratiotimes for the above show is (index page https://immediate-prod.apigee.net//broadcast/v1/schedule?startdate=14-04-2019%2000:00:00&hours=24&totalwidthunits=0&channels=11314)

StartTimeMF | "2019-04-14 21:00:00Z"

while it should be Zulu time it's actually British time

**Comment by Pancronos** [comment]
Probably you do not understand the difference,  but if you happy so......After 15 revisions, nobody changed that, guess why.

**Comment by olivluca** [comment]
I do understand the difference, but if you look at the example data I posted, you'll see that, while claiming it's zulu time it's actually giving the hour in British time: "Line of Duty" starts at 21:00 british time and the json says "21:00:00Z".
If you click on the link provided above with firefox it will show the decoded json (chrome only shows it raw), so it's easy to see.
Maybe they've just changed it in now, that's why nobody noticed. Or maybe somebody else noticed but didn't bother to modify the ini and create a pull request (yet).
Oh, and I found another error with the episode number (the second number is not the season but the number of episodes in the current season).
I patched my copy to get the episode and season from the link.

**Comment by olivluca** [comment]
Oh, and somebody **did** change it in revision 15

**Comment by olivluca** [comment]
Here's a screenshot of the data from radiotimes for the above show. As you can see it's reporting 21:00:00Z in StartTimeMF and 9pm as StartTime. If you check any bbc listing for Line of Duty you'll see it starts at 21:00 **british time**
Imgur  [](url)

**Comment by olivluca** [comment]
Never mind, I now use tvguide.co.uk.ini. It works out of the box with the correct times, correct episode number, channel icons and better resolution show icons.
I wish I tried that before losing my time fixing this broken ini.

**Pull request closed without merging**
