### PR TITLE
Update bnet.hr.ini

### PR DESCRIPTION
**Pull request by Netuddki**

### CODE REVIEW

**Comment by muzena** [comment]
@Netuddki 
Thanks!
Can you update also https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/master/siteini.pack/Croatia/mojtv.hr.ini
To grab more details; episode number for tv shows, ratings etc...
And I think that need mojtv.hr.channels.xml also update for new channels.

**Comment by Netuddki** [comment]
@muzena 
I think it's the same as mojtv.net.
You can just change the net into hr.
But I will look at it later.

**Comment by muzena** [comment]
@Netuddki 
I try this but dosen't work.

**Comment by Netuddki** [comment]
@muzena 
Added the fixed ini to github.
Update your channel list!

**Comment by Netuddki** [comment]
@muzena 
Added updated ini for mojnet.hr
Update your channel list as well!

**Comment by muzena** [comment]
@Netuddki 
Can you add support for HRT?
http://raspored.hrt.hr/
http://raspored.hrt.hr/format/xmltv.xml?mreza=2

**Comment by Netuddki** [comment]
HRT/HTV is supported in all croation inis, isn't it?

**Comment by muzena** [comment]
@Netuddki 
They sometimes change TV shema and TV shows and then is more accurate their TV schedule.

**Pull request merged**
