### PR TITLE
Update dsmart.com.tr.ini

### PR DESCRIPTION
**Pull request by Netuddki**

### CODE REVIEW

**Comment by SilentButeo2** [comment]
Could you add windows version too?

**Comment by Netuddki** [comment]
It doesn't work on windows unfortunately.
But I will try more.

**Comment by SilentButeo2** [comment]
Strange, because I thought the .php script was only needed to fix a mono issue with https requests?

**Comment by Netuddki** [comment]
I know, but I tried and it didn't work.
I will experiment further.

**Comment by Netuddki** [comment]
So, I tried again.
On windows you always get an error message:

**_"error downloading page: Die zugrunde liegende Verbindung wurde geschlossen: Unerwarteter Fehler beim Senden.."_**

Which roughly means that the connection is closed due to an unexpected failure

**Pull request closed without merging**
