### PR TITLE
Create cosmote-onscreenepisodes.gr.channels.xml

### PR DESCRIPTION
**Pull request by Netuddki**

### CODE REVIEW

**Comment by SilentButeo2** [comment]
Thanks, but I don't think this will work? Site is not the same as the siteini name?
Or see I thinks wrong?

**Comment by Netuddki** [comment]
The ini works with the normal cosmo.gr site.
I just didn't know how to differentiate the ini from the other ini, that's why I added the "-onscreenepisodes" suffix.

**Comment by SilentButeo2** [comment]
I such a situation, we normally start from the xmltv-ns version and add a modify at the end of the siteini. That way, you only need to support one siteini.
So if the user wants to use the xmlt-ns, it can comment out the modify (to onscreen).
But I don't know if that is possible for this site?

**Comment by Netuddki** [comment]
The site uses onscreen episode system originally.
Anot just made a bunch of rewrites to get the xmlt-ns system.
He made many replaces and removes from E01S01 to get those 1.1 formats (I am not really familiar with the xmlt-ns system, so I just made that 1.1 up... no clue how it looks exactly)

**Comment by Netuddki** [comment]
I don't know what to do. Anot's ini is very heavy on code, which I don't even understand fully, what he does with it and he even has some mistakes in it with the rating system, which I could fix, but I don't really want to mess with his code.

I don't know how we were able to merge the two very different approaches, so it's up to you to decide, what you want to do.

Maybe Anot will look at both versions and he are willing to merge them.
I can't.
I use my version, because it's lighter and for me more suitable.

**Pull request closed without merging**
