### PR TITLE
Add python version of add-logo postprocess plugin

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
Usage example:

```python
python add_logo.py --xmltv_in=guide.xml --logos=my_logos.ini --xmltv_out guide_with_logo.xml
```

### CODE REVIEW

**Comment by WGMaker** [comment]
Interesting! Same functionality as the C# original ?

**Comment by thiagocrepaldi** [comment]
yes, the only difference is how the arguments is passed to the add_logo script. I used the argparse library, which is more idiomatic to python

**Comment by Pancronos** [comment]
Appreciate your interest.

**Comment by Pancronos** [comment]
Forgot to mention if you can add a txt file on how to run on windows/linux, if additional software needs to be installed, etc. etc.
Thanks !!

**Comment by WGMaker** [comment]
Hi MatCron  ..

I am currently very busy finalising a next beta of the program. Therefore, no time to write (incl the always required testing if all correct) that. But maybe it helps that the latest WG++ version 5.1 and up supports postprocess plugins that are compiled to run in platform independent dotnet . For that it must be compiled as .dll. or any other executable that runs in dotnet. Supposing that can be done in python ( really no experience with that) in WebGrab++.config.xml specify
for all platforms that have dotnet installed:
  <postprocess run="y" grab="y or n">dotnet YourPostprocessAddonDotnetExecutable  args
windows only :
  <postprocess run="y" grab="y or n"> YourPostprocessAddonWindowsExecutable args

Keep me posted     Jan

**Comment by thiagocrepaldi** [comment]
> Forgot to mention if you can add a txt file on how to run on windows/linux, if additional software needs to be installed, etc. etc. Thanks !!

https://github.com/SilentButeo2/webgrabplus-siteinipack/pull/561 here you go

**Pull request merged**
